version: '3'
services:
  cyanfox-base:
    container_name: cyanfox-base
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
