version: '3'
services:
  # Application
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # MySQL
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testing
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
