name: Build Docker Image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - v3

jobs:
  push:
    name: "cyanfox-projects/base"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.image
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/cyanfox-projects/cyanfox-base:latest
