name: Release

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.1-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: '8.1'
          extensions: gd, intl, zip
          coverage: none
          tools: composer:v2

  test:
    needs: install
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.1-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          cp .env.testing .env
          composer update
          npm install
          docker-compose -f docker-compose.test.yml up -d
          docker exec template_app npm run build
          docker exec template_app php artisan test
