name: Test

on:
  push:
    branches:
      - develop
      - v3
  pull_request:
    branches:
      - develop
      - v3
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, gd, iconv, fileinfo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: |
          cp .env.testing .env
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          /usr/local/bin/composer update

          ./vendor/bin/sail up -d
          ./vendor/bin/sail npm install
          ./vendor/bin/sail npm run build
          ./vendor/bin/sail test
