name: Test

on:
  push:
    branches:
      - v2
      - develop
  pull_request:
    branches:
      - v2
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Composer Install & Update
        run: |
          composer install
          composer update

      - name: Test
        run: |
          cp .env.testing .env
          docker-compose -f docker-compose.test.yml up -d
          docker exec laravel.test composer update
          docker exec laravel.test npm install
          docker exec laravel.test npm run build
          docker exec laravel.test php artisan test --coverage --min=80 --env=testing
