name: Test

on:
  push:
    branches:
      - v2
      - develop
  pull_request:
    branches:
      - v2
      - develop

jobs:
  test:
    needs: install
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.1-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          cp .env.testing .env
          docker-compose -f docker-compose.test.yml up -d
          docker exec template_app composer update
          docker exec template_app npm install
          docker exec template_app npm run build
          docker exec template_app php artisan test
